name: Publish NPM

run-name: Publish NPM - ${{ github.event.inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        required: true
        description: 'Which package to release'
        options:
          - ilanzou
          - log
          - utils

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: setup repo
        uses: actions/checkout@v4

      - name: verify package exists
        run: ls packages/${{ github.event.inputs.package }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: npm install
        run: pnpm install

      - name: build
        run: pnpm build

      - name: publish
        working-directory: packages/${{ github.event.inputs.package }}
        run: npm publish --access=public
